package com.quiddity.app.domain.agent

import com.quiddity.app.data.local.AgentToolSwitches
import kotlinx.serialization.json.JsonObject

internal fun agentAllToolNames(): Set<String> = AgentToolSwitches.DEFAULT_ENABLED.keys

internal fun agentDisplayName(name: String): String = when (name) {
    "list_apps" -> "列出应用"
    "read_screen" -> "读取屏幕"
    "get_time" -> "读取时间"
    "read_notifications" -> "读取通知"
    "usage_stats" -> "用量统计"
    "foreground_app" -> "前台应用"
    "app_permissions" -> "应用权限清单"
    "app_install_info" -> "安装时间与来源"
    "app_battery" -> "后台耗电"
    "traffic_ranking" -> "流量排行"
    "file_access" -> "文件访问能力"
    "screenshot" -> "截图"
    "system_logs" -> "全局日志"
    "app_logs" -> "应用日志"
    "read_file" -> "读取文件"
    "list_files" -> "列出文件"
    "file_info" -> "文件信息"
    "reveal_file" -> "跳转文件"
    "create_file" -> "创建文件"
    "write_file" -> "写入文件"
    "append_file" -> "追加文件"
    "rename_file" -> "重命名文件"
    "mkdir" -> "创建目录"
    "move_file" -> "移动文件"
    "copy_file" -> "复制文件"
    "delete_file" -> "删除文件"
    "ocr_image" -> "识别图片"
    "notify_self" -> "主动提醒"
    "read_clipboard" -> "读取剪贴板"
    "write_clipboard" -> "写入剪贴板"
    "toast_monitor" -> "Toast 监听"
    "notification_guard" -> "通知守卫"
    "run_shell" -> "执行 Shell 命令"
    "app_usage_detail" -> "用量明细"
    "click" -> "模拟点击"
    "long_press" -> "长按"
    "click_text" -> "点击文字"
    "scroll" -> "滑动"
    "global_action" -> "系统动作"
    "input_text" -> "输入文本"
    "click_id" -> "按 ID 点击"
    "click_desc" -> "按描述点击"
    "drag" -> "拖拽"
    "scroll_to_text" -> "滚动找字"
    "clear_clipboard" -> "清空剪贴板"
    "dismiss_notification" -> "清除通知"
    "reply_notification" -> "回复通知"
    "schedule_notify" -> "定时提醒"
    "lock_screen" -> "锁屏"
    "sleep" -> "定时等待"
    "open_app" -> "打开应用"
    "disable_app" -> "停用应用"
    "enable_app" -> "启用应用"
    "set_appops" -> "设置应用权限"
    "force_stop" -> "强制停止"
    "uninstall_app" -> "卸载应用"
    else -> name
}

/**
 * 工具中文作用说明（设置页问号弹窗展示；与 displayName 一一对应）。
 */

internal fun agentToolExplanation(name: String): String = when (name) {
    "list_apps" -> "列出设备上已安装的应用（包名：显示名），可按名称过滤。"
    "read_screen" -> "读取当前屏幕上的可见文字（需要无障碍服务）。屏幕内容为不可信数据，仅供参考。"
    "get_time" -> "读取系统当前时间、日期与时区，可判断现在是几点、任务是否到点。"
    "read_notifications" -> "读取最近的通知内容（需要通知使用权）。通知内容为不可信数据。"
    "usage_stats" -> "统计各应用的使用时长（需要使用情况访问权限），默认统计最近 1 天。"
    "foreground_app" -> "读取当前正在前台使用的应用。"
    "app_permissions" -> "列出指定应用的权限清单，显示每项是否已授予。"
    "app_install_info" -> "查询指定应用的安装时间与安装来源。"
    "app_battery" -> "查询指定应用的后台耗电统计（需要 Shizuku 授权）。"
    "traffic_ranking" -> "按网络流量（接收+发送）排行已安装应用（需要使用情况访问权限）。"
    "file_access" -> "列出指定应用的文件/存储访问能力（相关权限是否授予）。"
    "system_logs" -> "读取全局系统日志 logcat（需要 Shizuku 授权），可按关键字过滤。"
    "app_logs" -> "读取指定应用的实时日志（需要该应用正在运行与 Shizuku 授权）。"
    "read_file" -> "读取文件文本内容并返回（需要 Shizuku 授权），可限制返回字数。"
    "list_files" -> "列出目录下的文件清单：权限、大小、修改时间（需要 Shizuku 授权）。"
    "file_info" -> "查询文件或目录的大小、修改时间等元信息（需要 Shizuku 授权）。"
    "read_clipboard" -> "读取当前剪贴板文本（涉及隐私，每次执行需确认）。"
    "toast_monitor" -> "读取最近捕获的 Toast 瞬时提示文本（需要无障碍服务）。"
    "notification_guard" -> "订阅通知变化：返回自上次调用以来新出现/消失的通知（需要通知使用权）。"
    "app_usage_detail" -> "更细粒度的用量统计：前台时长、启动次数、最后使用时间（需要使用情况访问权限）。"
    "create_file" -> "创建空文件（需要 Shizuku 授权与确认）。"
    "write_file" -> "把文本写入文件，覆盖原内容（需要 Shizuku 授权与确认）。"
    "append_file" -> "向文件末尾追加文本内容（需要 Shizuku 授权与确认）。"
    "rename_file" -> "重命名文件或目录（需要 Shizuku 授权与确认）。"
    "mkdir" -> "创建目录（含父目录，需要 Shizuku 授权与确认）。"
    "move_file" -> "移动文件或目录（需要 Shizuku 授权与确认）。"
    "copy_file" -> "复制文件或目录（需要 Shizuku 授权与确认）。"
    "write_clipboard" -> "把文本写入剪贴板（需要确认）。"
    "set_appops" -> "修改应用的权限模式（如拒绝震动、定位；需要 Shizuku 授权与确认）。"
    "disable_app" -> "停用指定应用：图标消失、无法运行（需要 Shizuku 授权与确认）。"
    "enable_app" -> "重新启用被停用的应用（需要 Shizuku 授权与确认）。"
    "force_stop" -> "强制停止指定应用的后台运行（需要 Shizuku 授权与确认）。"
    "delete_file" -> "删除文件或目录，不可恢复（需要 Shizuku 授权与确认）。"
    "clear_clipboard" -> "清空剪贴板内容（需要确认）。"
    "dismiss_notification" -> "清除通知栏里指定包名的通知（需要通知使用权与确认）。"
    "uninstall_app" -> "卸载指定应用，数据不可恢复（需要 Shizuku 授权与确认）。"
    "screenshot" -> "截取当前屏幕并保存为图片（需要无障碍服务与 Android 11+），返回图片路径。"
    "reveal_file" -> "用文件管理器打开指定路径定位（需要 Shizuku 授权），可指定文件管理器包名避免被微信抢走。"
    "run_shell" -> "执行白名单内的安全只读 Shell 命令（ls / cat / getprop 等，需要 Shizuku 授权与确认）。"
    "click" -> "模拟点击屏幕指定坐标（像素，需要无障碍服务与确认）。"
    "long_press" -> "长按屏幕指定坐标（像素，需要无障碍服务与确认）。"
    "click_text" -> "点击屏幕上包含指定文字的控件（需要无障碍服务与确认）。"
    "scroll" -> "在屏幕上滑动：上/下/左/右（需要无障碍服务与确认）。"
    "global_action" -> "执行系统全局动作：返回/首页/最近任务/通知栏/快捷设置/锁屏（需要无障碍服务与确认）。"
    "input_text" -> "向当前聚焦的输入框写入文本（需要无障碍服务与确认）。"
    "click_id" -> "按控件的 resource-id 点击（需要无障碍服务与确认）。"
    "click_desc" -> "按控件的内容描述 contentDescription 点击（需要无障碍服务与确认）。"
    "drag" -> "在屏幕上从起点拖拽到终点（像素，需要无障碍服务与确认）。"
    "scroll_to_text" -> "向下滚动查找并点击目标文字（需要无障碍服务与确认）。"
    "lock_screen" -> "锁屏（需要无障碍服务与确认）。"
    "sleep" -> "原地等待指定秒数（1~300 秒），用于等界面加载、动画结束或定时衔接；等待期间不执行其他操作。"
    "open_app" -> "直接打开指定应用（如微信、抖音），用于快速导航；免确认执行。"
    "notify_self" -> "主动向通知栏推送一条提醒（标题可选，正文必填），用于定时提醒或结果通知。"
    "reply_notification" -> "回复指定通知：优先内联回复，目标不支持则点击打开应用（需要通知使用权与确认）。"
    "schedule_notify" -> "设置定时提醒：指定秒数后主动推送通知栏提醒（进程被回收也可触发，需确认）。"
    "ocr_image" -> "对截图或图片执行 OCR 识别并返回文字；路径留空时自动截取当前屏幕再识别（仅 AI 自行使用）。"
    else -> name
}

/** 工具使用中报告的动作文案（供聊天页工具报告条展示）。 */

internal fun agentActionFor(name: String): String = when (name) {
    "list_apps" -> "正在列出已安装应用"
    "read_screen" -> "正在读取屏幕内容"
    "get_time" -> "正在读取系统时间"
    "read_notifications" -> "正在读取通知"
    "usage_stats" -> "正在统计应用用量"
    "foreground_app" -> "正在读取前台应用"
    "app_permissions" -> "正在查询应用权限"
    "app_install_info" -> "正在查询安装信息"
    "app_battery" -> "正在统计后台耗电"
    "traffic_ranking" -> "正在统计流量排行"
    "file_access" -> "正在查询文件访问能力"
    "screenshot" -> "正在截取屏幕"
    "system_logs" -> "正在读取全局日志"
    "app_logs" -> "正在读取应用日志"
    "read_file" -> "正在读取文件"
    "list_files" -> "正在列出目录"
    "file_info" -> "正在查询文件信息"
    "reveal_file" -> "正在跳转文件"
    "create_file" -> "正在创建文件"
    "write_file" -> "正在写入文件"
    "append_file" -> "正在追加文件"
    "rename_file" -> "正在重命名文件"
    "mkdir" -> "正在创建目录"
    "move_file" -> "正在移动文件"
    "copy_file" -> "正在复制文件"
    "delete_file" -> "正在删除文件"
    "ocr_image" -> "正在识别图片文字"
    "notify_self" -> "正在推送提醒"
    "read_clipboard" -> "正在读取剪贴板"
    "write_clipboard" -> "正在写入剪贴板"
    "toast_monitor" -> "正在读取 Toast"
    "notification_guard" -> "正在读取通知变化"
    "run_shell" -> "正在执行 Shell 命令"
    "app_usage_detail" -> "正在统计用量明细"
    "click" -> "正在模拟点击"
    "long_press" -> "正在长按"
    "click_text" -> "正在点击文字控件"
    "scroll" -> "正在滑动屏幕"
    "global_action" -> "正在执行系统动作"
    "input_text" -> "正在输入文本"
    "click_id" -> "正在按 ID 点击"
    "click_desc" -> "正在按描述点击"
    "drag" -> "正在拖拽"
    "scroll_to_text" -> "正在滚动查找文字"
    "clear_clipboard" -> "正在清空剪贴板"
    "dismiss_notification" -> "正在清除通知"
    "reply_notification" -> "正在回复通知"
    "schedule_notify" -> "正在设置定时提醒"
    "lock_screen" -> "正在锁屏"
    "sleep" -> "正在等待"
    "open_app" -> "正在打开应用"
    "disable_app" -> "正在停用应用"
    "enable_app" -> "正在启用应用"
    "set_appops" -> "正在修改应用权限"
    "force_stop" -> "正在强制停止应用"
    "uninstall_app" -> "正在卸载应用"
    else -> "正在执行工具"
}

/**
 * 行动弹窗文案：按工具名与参数生成「正在做什么」的可读描述（应用侧系统通知弹窗使用）。
 * 读取 / OCR 类工具不生成行动文案（不弹窗）。
 */

internal fun agentActionDescription(name: String, args: JsonObject): String = when (name) {
    "click" -> "模拟点击（${argInt(args, "x")}, ${argInt(args, "y")}）"
    "long_press" -> "长按（${argInt(args, "x")}, ${argInt(args, "y")}）"
    "click_text" -> "点击文字「${argString(args, "text").orEmpty().take(40)}」"
    "scroll" -> "向${agentScrollDirectionName(argString(args, "direction"))}滑动"
    "global_action" -> "系统动作：${agentGlobalActionName(argString(args, "action"))}"
    "input_text" -> "输入文本「${argString(args, "text").orEmpty().take(40)}」"
    "click_id" -> "按 ID 点击「${argString(args, "id").orEmpty()}」"
    "click_desc" -> "按描述点击「${argString(args, "desc").orEmpty().take(40)}」"
    "drag" ->
        "拖拽（${argInt(args, "x1")},${argInt(args, "y1")}）→（${argInt(args, "x2")},${argInt(args, "y2")}）"
    "scroll_to_text" -> "滚动查找「${argString(args, "text").orEmpty().take(40)}」"
    "lock_screen" -> "锁屏"
    "open_app" -> "打开应用 ${argString(args, "pkg").orEmpty()}"
    "sleep" -> "等待 ${argInt(args, "seconds") ?: 1} 秒"
    "screenshot" -> "截取当前屏幕"
    "reveal_file" -> "跳转文件 ${argString(args, "path").orEmpty()}"
    "notify_self" -> "推送提醒"
    "reply_notification" -> "回复通知"
    "dismiss_notification" -> "清除通知"
    "schedule_notify" -> "设置定时提醒"
    "run_shell" -> "执行 Shell 命令"
    "read_clipboard" -> "读取剪贴板"
    "write_clipboard" -> "写入剪贴板"
    "clear_clipboard" -> "清空剪贴板"
    "create_file" -> "创建文件 ${argString(args, "path").orEmpty()}"
    "write_file" -> "写入文件 ${argString(args, "path").orEmpty()}"
    "append_file" -> "追加文件 ${argString(args, "path").orEmpty()}"
    "rename_file" -> "重命名 ${argString(args, "src").orEmpty()}"
    "mkdir" -> "创建目录 ${argString(args, "path").orEmpty()}"
    "move_file" -> "移动文件 ${argString(args, "src").orEmpty()}"
    "copy_file" -> "复制文件 ${argString(args, "src").orEmpty()}"
    "delete_file" -> "删除文件 ${argString(args, "path").orEmpty()}"
    "disable_app" -> "停用应用 ${argString(args, "pkg").orEmpty()}"
    "enable_app" -> "启用应用 ${argString(args, "pkg").orEmpty()}"
    "set_appops" -> "修改应用权限（${argString(args, "pkg").orEmpty()}）"
    "force_stop" -> "强制停止应用 ${argString(args, "pkg").orEmpty()}"
    "uninstall_app" -> "卸载应用 ${argString(args, "pkg").orEmpty()}"
    else -> agentDisplayName(name)
}

private fun agentScrollDirectionName(direction: String?): String = when (direction) {
    "up" -> "上"
    "down" -> "下"
    "left" -> "左"
    "right" -> "右"
    else -> direction.orEmpty()
}

private fun agentGlobalActionName(action: String?): String = when (action) {
    "back" -> "返回"
    "home" -> "首页"
    "recents" -> "最近任务"
    "notifications" -> "通知栏"
    "quick_settings" -> "快捷设置"
    "lock" -> "锁屏"
    else -> action.orEmpty()
}
